import { createServer } from "miragejs";



export const myServer = () => {
  createServer({
    routes() {
      this.namespace = "api";

      this.get("/posts", [
          { title: "MyLorem1", body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia culpa, ullam maxime at vel deserunt distinctio ipsam aliquam provident laboriosam impedit tenetur hic magni excepturi veniam facilis. Sint, neque. Quasi.= Eos, placeat illum reprehenderit velit molestiae dolorem expedita consequuntur nostrum iure ipsa sequi aperiam autem deleniti tempora natus adipisci nihil voluptate ducimus pariatur! Quisquam perferendis exercitationem eveniet, repellendus aspernatur vitae!Molestias sed magni sapiente! Nam dolores laborum repellat repellendus architecto maxime sapiente quaerat voluptate? Explicabo eos cumque, minus nam repellat neque ducimus. Ullam voluptatem sapiente hic dolores autem eligendi tempora!Iusto, tenetur qui sed facere harum, laudantium magnam maiores inventore vero odio nemo fugiat molestias adipisci atque vel, illo quisquam nostrum maxime. Possimus facilis, minima eaque pariatur consequuntur architecto quaerat.Porro, rerum saepe. Quis nostrum pariatur corporis tempora minima perspiciatis nobis quaerat amet a? Esse iusto dignissimos voluptatibus recusandae sint sit, placeat dolores accusantium eveniet asperiores quis quas odio incidunt. empora natus adipisci nihil voluptate ducimus pariatur! Quisquam perferendis exercitationem eveniet, repellendus aspernatur vitae!Molestias sed magni sapiente! Nam dolores laborum repellat repellendus architecto maxime sapiente quaerat voluptate? Explicabo eos cumque, minus nam repellat neque ducimus. Ullam voluptatem sapiente hic dolores autem eligendi tempora!Iusto, tenetur qui sed facere harum, laudantium magnam maioresempora natus adipisci nihil voluptate ducimus pariatur! Quisquam perferendis exercitationem eveniet, repellendus aspernatur vitae!Molestias sed magni sapiente! Nam dolores laborum repellat repellendus architecto maxime sapiente quaerat voluptate? Explicabo eos cumque, minus nam repellat neque ducimus. Ullam voluptatem sapiente hic dolores autem eligendi tempora!Iusto, tenetur qui sed facere harum, laudantium magnam maiores', author: "Victor", id: 1 },
          { title: "MyLorem2", body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia culpa, ullam maxime at vel deserunt distinctio ipsam aliquam provident laboriosam impedit tenetur hic magni excepturi veniam facilis. Sint, neque. Quasi.= Eos, placeat illum reprehenderit velit molestiae dolorem expedita consequuntur nostrum iure ipsa sequi aperiam autem delenres inventore vero odio nemo fugiat molestias adipisci atque vel, illo quisquam nostrum maxime. Possimus facilis, minima eaque pariatur consequuntur architecto quaerat.Porro, rerum saepe. Quis nostrum pariatur corporis tempora minima perspiciatis nobis quaerat amet a? Esse iusto dignissimos voluptatibus recusandae sint sit, placeat dolores accusantium eveniet asperiores quis quas odio incidunt.', author: "Amanda", id: 2 },
          { title: "MyLorem3", body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia culpa, ullam maxime at vel deserunt distinctio ipsam aliquam provident laboriosam impedit tenetur hic magni excepturi veniam facilis. Sint, neque. Quasi.= Eos, placeat illum reprehenderit velit molestiae dolorem expedita consequuntur nostrum iure ipsa sequi aperiam autem deleniti tempora natus adipisci nihil voluptate ducimus pariatur! Quisquam perferendis exercitationem eveniet, repellendus aspernatur vitae!Molestias sed magni sapiente! Nam dolores laborum repellat repellendus architecto maxime sapiente quaerat voluptate? Explicabo eos cumque, minus nam repellat neque ducimus. Ullam voluptatem sapiente hic dolores autem eligendi tempora!Iusto, tenetur qui sed facere harum, laudantium magnam maiores inventore vero odio nemo fugiat molestias adipisci atque vel, illo quisquam nostrum maxime. Possimus facilis, minima eaque pariatur consequuntur architecto quaerat.Porro, rerum saepe. Quis nostrum pariatur corporis tempora minima perspiciatis nobis quaerat amet a? Esse iusto dignissimos voluptatibus recusandae sint sit, placeat dolores accusantium eveniet asperiores quis quas odio incidunt.d magni sapiente! Nam dolores laborum repellat repellendus architecto maxime sapiente quaerat voluptate? Explicabo eos cumque, minus nam repellat neque ducimus. Ullam voluptatem sapiente hic dolores autem eligendi tempora!Iusto, tenetur qui sed facere harum, laudantium magnam maiores invent', author: "Sam", id: 3 },
          { title: "MyLorem4", body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia culpa, ullam maxime at vel deserunt distinctio ipsam aliquam provident laboriosam impedit tenetur hic magni excepturi veniam facilis. Sint, neque. Quasi.= Eos, placeat illum reprehenderit velit molestiae dolorem expedita consequuntur nostrum iure ipsa sequi aperiam autem deleniti tempora natus adipisci nihil voluptate ducimus pariatur! Quisquam perferendis exercitationem eveniet, repellendus aspernatur vitae!Molestias sed magni sapiente! Nam dolores laborum repellat repellendus architecto maxime sapiente quaerat voluptate? Explicabo eos cumque, minus nam repellat neque ducimus. Ullam voluptatem sapiente hic dolores autem eligendi tempora!Iusto, tenetur qui sed facere harum, laudantium magnam maiorris tempora minima perspiciatis nobis quaerat amet a? Esse iusto dignissimos voluptatibus recusandae sint sit, placeat dolores accusantium eveniet asperiores quis quas odio incidunt.', author: "Mel", id: 4 },
      ]);
    },
  });
};



